# -*- coding: utf-8 -*-
"""GEOG 450: Lab3 Final Infographic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xx3xqcgkeb1DS0_r0mFx1YVaKgxCukzi

Lab 3 (Group 8): Henry, Son, Nikita, Andy
"""

import pandas as pd
import altair as alt

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
upload = files.upload()

data = pd.read_csv("30datesupdated (1).csv")

data = pd.read_csv("30datesupdated (1).csv")
group_data = data.groupby(['date', 'color'])['percentage'].sum().reset_index()
colors = alt.Scale(domain=data['color'].unique(), range=data['color'].unique())

bar_chart = alt.Chart(group_data).mark_bar().encode(
    x=alt.X('percentage:Q', stack='normalize', title='Percentage', axis=alt.Axis(format='%')),
    y=alt.Y('date:N', axis=alt.Axis(title='Date')),
    color=alt.Color('color:N', scale=colors, legend=None)
).properties(
    title= 'UW Clothing Colors (Red Square)'
)

names = 'Henry, Son, Nikita, Andy'
add_name = alt.Chart().mark_text(
    text=names,
    fontSize=8,
    align='right',
    baseline='bottom',
).encode(
    x=alt.value(488),
    y=alt.value(655),
)

create_chart = alt.layer(bar_chart, add_name)
create_chart
