# -*- coding: utf-8 -*-
"""Testing Image Processing:Lab 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qOe1Trwb9tIaCQ0MD6FetAtTe5LSVBpq
"""

from google.colab import drive
drive.mount('/content/drive')

pip install Pillow

drive.mount("/content/drive", force_remount=True)

import glob
from PIL import Image
import os

input_folder = "/content/drive/MyDrive/GEOG450/testinglab3/"
output_folder = "/content/drive/MyDrive/GEOG450/testinglab3/results"

#images = glob.glob("/content/drive/MyDrive/GEOG450/testinglab3/*.jpg")
images = glob.glob(os.path.join(input_folder, "*.jpg"))
for image in images:
    with open(image, 'rb') as file:
        im = Image.open(file)
        print(im.format, im.size, im.mode)
        im.show()

        result = im.convert('P', palette=Image.ADAPTIVE, colors=10)
        # Get the filename without extension
        filename = os.path.splitext(os.path.basename(image))[0]

        # Save the processed image with a unique filename
        result.save(os.path.join(output_folder, f"{filename}_result.png"))

"""### Everything below this is untouched and from the colab notebook template we were given"""

from PIL import ImageColor

import numpy as np
from PIL import Image

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1004_result.png')# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

colours, counts

def rgb_to_hex(rgb):
    return '#%02x%02x%02x' % rgb

for i in range(colours.shape[0]):
    print(colours[i], rgb_to_hex((colours[i,0],colours[i,1],colours[i,2])), counts[i])

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)
print(myhex)

totalpixel = sum(counts)
totalpixel

import pandas as pd

df = pd.DataFrame(columns=['date','colorhex','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])
df

df['date']='2/7/2024 9:00'
df['color']=myhex
df['numpixel']= np.int_(counts)
df['percentage']=(df.numpixel/totalpixel)*100;
df

df.to_csv(r'/content/drive/MyDrive/finish (csv)/result1.csv')

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/finish (csv)/result1.csv')
print(df)

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1005_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df2 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df2['date']='2/7/2024 9:12'
df2['color']=myhex
#df2['color']=df2['color'].apply(lambda x: "'" + str(x) + "'")
df2['numpixel']= np.int_(counts)
df2['percentage']=(df2.numpixel/totalpixel)*100;
df2
df2.to_csv(r'/content/drive/MyDrive/finish (csv)/result2.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1007_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df3 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df3['date']='2/7/2024 9:24'
df3['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df3['numpixel']= np.int_(counts)
df3['percentage']=(df3.numpixel/totalpixel)*100;
df3
df3.to_csv(r'/content/drive/MyDrive/finish (csv)/result3.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1009_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df4 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df4['date']='2/7/2024 9:36'
df4['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df4['numpixel']= np.int_(counts)
df4['percentage']=(df3.numpixel/totalpixel)*100;
df4
df4.to_csv(r'/content/drive/MyDrive/finish (csv)/result4.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1011_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df5 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df5['date']='2/7/2024 9:48'
df5['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df5['numpixel']= np.int_(counts)
df5['percentage']=(df3.numpixel/totalpixel)*100;
df5
df5.to_csv(r'/content/drive/MyDrive/finish (csv)/result5.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1012_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df6 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df6['date']='2/7/2024 10:00'
df6['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df6['numpixel']= np.int_(counts)
df6['percentage']=(df3.numpixel/totalpixel)*100;
df6
df6.to_csv(r'/content/drive/MyDrive/finish (csv)/result6.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1014_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df7 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df7['date']='2/7/2024 10:12'
df7['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df7['numpixel']= np.int_(counts)
df7['percentage']=(df3.numpixel/totalpixel)*100;
df7
df7.to_csv(r'/content/drive/MyDrive/finish (csv)/result7.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1016_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df8 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df8['date']='2/7/2024 10:24'
df8['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df8['numpixel']= np.int_(counts)
df8['percentage']=(df3.numpixel/totalpixel)*100;
df8
df8.to_csv(r'/content/drive/MyDrive/finish (csv)/result8.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1017_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df9 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df9['date']='2/7/2024 10:36'
df9['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df9['numpixel']= np.int_(counts)
df9['percentage']=(df3.numpixel/totalpixel)*100;
df9
df9.to_csv(r'/content/drive/MyDrive/finish (csv)/result9.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1020_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df10 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df10['date']='2/7/2024 10:48'
df10['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df10['numpixel']= np.int_(counts)
df10['percentage']=(df3.numpixel/totalpixel)*100;
df10
df10.to_csv(r'/content/drive/MyDrive/finish (csv)/result10.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1026_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df11 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df11['date']='2/7/2024 11:00'
df11['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df11['numpixel']= np.int_(counts)
df11['percentage']=(df3.numpixel/totalpixel)*100;
df11
df11.to_csv(r'/content/drive/MyDrive/finish (csv)/result11.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1027_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df12 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df12['date']='2/8/2024 10:00'
df12['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df12['numpixel']= np.int_(counts)
df12['percentage']=(df3.numpixel/totalpixel)*100;
df12
df12.to_csv(r'/content/drive/MyDrive/finish (csv)/result12.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1028_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df13 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df13['date']='2/8/2024 10:10'
df13['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df13['numpixel']= np.int_(counts)
df13['percentage']=(df3.numpixel/totalpixel)*100;
df13
df13.to_csv(r'/content/drive/MyDrive/finish (csv)/result13.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1029_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df14 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df14['date']='2/8/2024 10:20'
df14['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df14['numpixel']= np.int_(counts)
df14['percentage']=(df3.numpixel/totalpixel)*100;
df14
df14.to_csv(r'/content/drive/MyDrive/finish (csv)/result14.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1030_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df15 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df15['date']='2/8/2024 10:30'
df15['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df15['numpixel']= np.int_(counts)
df15['percentage']=(df3.numpixel/totalpixel)*100;
df15
df15.to_csv(r'/content/drive/MyDrive/finish (csv)/result15.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1033_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df16 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df16['date']='2/8/2024 10:40'
df16['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df16['numpixel']= np.int_(counts)
df16['percentage']=(df3.numpixel/totalpixel)*100;
df16
df16.to_csv(r'/content/drive/MyDrive/finish (csv)/result16.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1034_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df17 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df17['date']='2/8/2024 10:50'
df17['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df17['numpixel']= np.int_(counts)
df17['percentage']=(df3.numpixel/totalpixel)*100;
df17
df17.to_csv(r'/content/drive/MyDrive/finish (csv)/result17.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1035_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df18 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df18['date']='2/8/2024 11:00'
df18['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df18['numpixel']= np.int_(counts)
df18['percentage']=(df3.numpixel/totalpixel)*100;
df18
df18.to_csv(r'/content/drive/MyDrive/finish (csv)/result18.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1036_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df19 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df19['date']='2/8/2024 11:10'
df19['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df19['numpixel']= np.int_(counts)
df19['percentage']=(df3.numpixel/totalpixel)*100;
df19
df19.to_csv(r'/content/drive/MyDrive/finish (csv)/result19.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_1037_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df20 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df20['date']='2/8/2024 11:20'
df20['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df20['numpixel']= np.int_(counts)
df20['percentage']=(df3.numpixel/totalpixel)*100;
df20
df20.to_csv(r'/content/drive/MyDrive/finish (csv)/result20.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/finish/IMG_1037_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df21 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df21['date']='2/8/2024 11:30'
df21['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df21['numpixel']= np.int_(counts)
df21['percentage']=(df3.numpixel/totalpixel)*100;
df21
df21.to_csv(r'/content/drive/MyDrive/finish (csv)/result21.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8366_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df22 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df22['date']='2/12/2024 14:00'
df22['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df22['numpixel']= np.int_(counts)
df22['percentage']=(df3.numpixel/totalpixel)*100;
df22
df22.to_csv(r'/content/drive/MyDrive/finish (csv)/result22.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8367_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df23 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df23['date']='2/12/2024 14:10'
df23['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df23['numpixel']= np.int_(counts)
df23['percentage']=(df3.numpixel/totalpixel)*100;
df23
df23.to_csv(r'/content/drive/MyDrive/finish (csv)/result23.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8368_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df24 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df24['date']='2/12/2024 14:20'
df24['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df24['numpixel']= np.int_(counts)
df24['percentage']=(df3.numpixel/totalpixel)*100;
df24
df24.to_csv(r'/content/drive/MyDrive/finish (csv)/result24.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8369_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df25 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df25['date']='2/12/2024 14:30'
df25['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df25['numpixel']= np.int_(counts)
df25['percentage']=(df3.numpixel/totalpixel)*100;
df25
df25.to_csv(r'/content/drive/MyDrive/finish (csv)/result25.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8371_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df26 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df26['date']='2/12/2024 14:40'
df26['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df26['numpixel']= np.int_(counts)
df26['percentage']=(df3.numpixel/totalpixel)*100;
df26
df26.to_csv(r'/content/drive/MyDrive/finish (csv)/result26.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8376_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df27 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df27['date']='2/12/2024 14:50'
df27['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df27['numpixel']= np.int_(counts)
df27['percentage']=(df3.numpixel/totalpixel)*100;
df27
df27.to_csv(r'/content/drive/MyDrive/finish (csv)/result27.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8378_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df28 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df28['date']='2/12/2024 15:00'
df28['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df28['numpixel']= np.int_(counts)
df28['percentage']=(df3.numpixel/totalpixel)*100;
df28
df28.to_csv(r'/content/drive/MyDrive/finish (csv)/result28.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8379_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df29 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df29['date']='2/12/2024 15:10'
df29['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df29['numpixel']= np.int_(counts)
df29['percentage']=(df3.numpixel/totalpixel)*100;
df29
df29.to_csv(r'/content/drive/MyDrive/finish (csv)/result29.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8380_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df30 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df30['date']='2/12/2024 15:20'
df30['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df30['numpixel']= np.int_(counts)
df30['percentage']=(df3.numpixel/totalpixel)*100;
df30
df30.to_csv(r'/content/drive/MyDrive/finish (csv)/result30.csv')

# Open image
im2 = Image.open('/content/drive/MyDrive/results/IMG_8381_result.png')

# Get palette and reshape into 3 columns
palette = np.array(im2.getpalette(),dtype=np.uint8).reshape((256,3))

# Convert Image to RGB and make into Numpy array
na = np.array(im2.convert('RGB'))

# Get used colours and counts of each
colours, counts = np.unique(na.reshape(-1,3), axis=0, return_counts=1)

myhex = []
for i in range(colours.shape[0]):
    data= rgb_to_hex((colours[i,0],colours[i,1],colours[i,2]))
    myhex.append(data)

totalpixel = sum(counts)

df31 = pd.DataFrame(columns=['date','color','numpixel','percentage'],
                 index=[0,1,2,3,4,5,6,7,8,9])

df31['date']='2/12/2024 15:30'
df31['color']=myhex
#df3['color']=df3['color'].apply(lambda x: "'" + str(x) + "'")
df31['numpixel']= np.int_(counts)
df31['percentage']=(df3.numpixel/totalpixel)*100;
df31
df31.to_csv(r'/content/drive/MyDrive/finish (csv)/result31.csv')

frames = [df, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df22, df23, df24, df25, df26, df27, df28, df29, df30, df31]
result = pd.concat(frames)
display(result)

result.to_csv(r'/content/drive/MyDrive/finish (csv)/all30df.csv')

print(result.keys())

columns_drop = ['Unnamed: 0.1', 'Unnamed: 0', 'colorhex']
result = result.drop(columns=columns_drop)

print(result.keys())

display(result)

result.to_csv(r'/content/drive/MyDrive/finish (csv)/finished30df.csv')
