# -*- coding: utf-8 -*-
"""Lab4_Chart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-55Eh3P4UtLbBpdcnMUfd1quvTx4i5r
"""

from google.colab import drive
drive.mount('/content/drive')

import json

with open('/content/drive/MyDrive/GEOG450/Lab4/Altered_Posts_Dataset_1.json') as json_file:
    Data = json.load(json_file)

Data

pip install plotly pandas

import pandas as pd
import plotly.express as px

df = pd.DataFrame(Data)

# Create a sunburst chart using plotly
fig = px.sunburst(df, path=['Category', 'Keywords'], title='Happy Places Are Inside and Outside!', width=1200, height =1200, color='Category')

caption_text = 'The divide between happy places inside<br>' \
                ' and happy places outside is pretty even,<br>' \
               'but the way people spend their time in the two types <br>'\
               'of environments are different.'

fig.update_layout(margin=dict(l=100, r=20, b=20, t=40),  # Adjust l value as needed
                  paper_bgcolor="white")

fig.add_annotation(
    text=caption_text,
    xref="paper", yref="paper",
    x=0, y=0.0001,
    showarrow=False,
    font=dict(size=14, color="black")
)

credit = '<i>Credit: Data created by Geog 450 WI24 class in Padlet<i>'
author = '<i>Author: Nikita Yadav<i>'
date_of_creation = '<i>Date of Creation: 3/01/2024<i>'

fig.update_layout(annotations=[
                               dict(x=0.99, y=0.04, xref='paper', yref='paper', text=author, showarrow=False, font=dict(size=8.5, color='black')),
                               dict(x=0.99, y=0.07, xref='paper', yref='paper', text=date_of_creation, showarrow=False, font=dict(size=8.5, color='black')),
                               dict(x=0.99, y=0.01, xref='paper', yref='paper', text=credit, showarrow=False, font=dict(size=8.5, color='black'))],
                  )

# Show the plot
fig.show()
